global using Task.domain.Entities;
global using AutoMapper;
global using MediatR;
global using TTask = System.Threading.Tasks.Task;
global using Task.Application.CommandsQueries.Commands;
global using Task.Application.CommandsQueries.Queries;
global using Task.Application.DTOs;
global using Task.domain.Interfaces;
global using Task.Application.Interfaces;
global using System.ComponentModel.DataAnnotations;
global using System.ComponentModel;